mqtt:
  enabled: false # Disable MQTT for this home‑project unless you need it

model:
  path: /config/models/dog_poop.pt
  width: 1920
  height: 1080
  labelmap:
    0: Dogpoop
    1: good
    
objects: 
  track:
    - Dogpoop
    - good

cameras:
  garden_cam:
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_CAM_USERNAME}:{FRIGATE_CAM_PASSWORD}@{FRIGATE_CAM_IP}:554/Streaming/Channels/101
          roles: [detect]
          
    detect:
      width: 1920
      height: 1080
      fps: 8

    # record:
    #   enabled: true
    #   retain:
    #     days: 3
    #     mode: all
    #   events:
    #     retain:
    #       default: 30

    # snapshots:
    #   enabled: true
    #   bounding_box: false
    #   retain:
    #     default: 3


# Optional: hardware acceleration examples (Intel Quick Sync / Nvidia / Coral)
# detectors:
#   coral:
#     type: edgetpu
#     device: usb